version: '3.1'
services:
  mongodb:
    image: mongo:3.4
    restart: "no"
    command: mongod --smallfiles
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-app:/var/www/html
    env_file:
      - ./.env
    ports:
      - 27017:27017
    networks:
      mongo_net:

  mongo-express:
    image: mongo-express
    container_name: mongoexpressweb
    restart: "no"
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    env_file:
      - ./.env
    networks:
      mongo_net:

  web:
    image: app
    restart:  unless-stopped
    container_name: djangoapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mentisparchment_docker
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - migration
    env_file:
      - ./.env
    networks:
      mongo_net:

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/mentisparchment_docker
    links:
      - mongodb
    depends_on:
      - make_migrations
    env_file:
      - ./.env
    networks:
      mongo_net:

  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/mentisparchment_docker
    links:
      - mongodb
    depends_on:
      - mongodb
    env_file:
      - ./.env
    networks:
      mongo_net:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01
#      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - mongo_net
    depends_on:
      - mongodb
    restart:  unless-stopped
#    es02:
#      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
#      container_name: es02
#      environment:
#        - node.name=es02
#        - cluster.name=es-docker-cluster
#        - discovery.seed_hosts=es01,es03
#        - cluster.initial_master_nodes=es01,es02,es03
#        - bootstrap.memory_lock=true
#        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      ulimits:
#        memlock:
#          soft: -1
#          hard: -1
#      volumes:
#        - data02:/usr/share/elasticsearch/data
#      networks:
#        - mongo_net
#      restart:  unless-stopped
#    es03:
#      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
#      container_name: es03
#      environment:
#        - node.name=es03
#        - cluster.name=es-docker-cluster
#        - discovery.seed_hosts=es01,es02
#        - cluster.initial_master_nodes=es01,es02,es03
#        - bootstrap.memory_lock=true
#        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      ulimits:
#        memlock:
#          soft: -1
#          hard: -1
#      volumes:
#        - data03:/usr/share/elasticsearch/data
#      networks:
#        - mongo_net
#      restart:  unless-stopped

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24

volumes:
  data01:
    driver: local
#  data02:
#    driver: local
#  data03:
#    driver: local